fix(contract): check constructor addresses
pooltogether/sushi-pooltogether pull request #16
Opened 2021-07-01 16:10 UTC by PierrickGT

Issue: https://github.com/code-423n4/2021-06-pooltogether-findings/issues/81

2021-07-05 22:59 UTC, asselstine requested changes

2021-07-05 22:59 UTC, asselstine commented on contracts/SushiYieldSource.sol
> +            address(_sushiBar).isContract(),
just check if zero!

2021-07-07 16:29 UTC, PierrickGT commented on contracts/SushiYieldSource.sol
> +            address(_sushiBar).isContract(),
Done: https://github.com/pooltogether/sushi-pooltogether/pull/16/commits/a99e3a455a94bee1169722f73f8a4f3de63cb81b

2021-07-07 18:20 UTC, asselstine approved these changes

2021-07-08 07:40 UTC, merged